project:
  type: website

website:
  title: ""  
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - about.qmd # About page
      - posts.qmd # Blog
    tools:
      - icon: twitter
        href: https://twitter.com/RHeirene

format:
  html:
    theme: solar
    css: styles.css
    toc: true


editor: visual
